### ISSUE TITLE
Added missing Dhall configuration options?

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#265]
In the initial issue, we were talking about adding Dhall into the configuration (https://github.com/input-output-hk/cardano-shell/issues/1).

Now the question is whether we need to add it for specific node modes (`real-pbft`, `mock-pbft`, `praos`, `bft`, `byron-legacy`).

So should we have Dhall configuration files for these?

**Comment by deepfire** [comment]
I think if we are adding text-based configuration files, that capacity should be uniform across node modes.

**Comment by deepfire** [comment]
Duncan raised a complicated question of whether we want Dhall, or maybe perhaps we could settle for just YAML. We've agonised over details with @cleverca22 for a while, and that's the rough summary:

1. Dhall configs have richer and hence more complex semantic, so therefore are less user-serviceable than the JSON/YAML (and also less familiar).
1. Using Dhall adds more complexity. In one instance, if we were to use Dhall in Daedalus, we'd have to either keep the extra step of Dhall->YAML transformation, or we would have to use https://github.com/Profpatsch/dhall-js
1. Dhall does quite strong type-checking out-of-the-box, and while we could use YAML validation by simply loading it using Aeson, that would not benefit from Dhall's stronger types, and better messages.
1. Dhall allows factoring of the configuration into separate files -- JSON/YAML have no mechanism for inclusion.
1. Dhall enables expression of context-dependent variability of configs by:
   - inclusion (i.e. you can import context-dependent subexpressions)
   - functional computation over context-dependent values
   We can see how this works in Daedalus:  https://github.com/input-output-hk/daedalus/tree/master/installers/dhall -- cluster and OS dependent pieces are factored, and have computations defined over them.
   YAML/JSON, in general would require having a product of all context-dependent axes to allow the same flexibility -- resulting in a maze of similar, but not quite files.
   This negative aspect of YAML/JSON could be somewhat compensated by moving some of the environment-dependency logic into the Haskell code (so we could have less than a full all-env-axes product of config files), but that would be adding complexity that could've otherwise been kept outside.

**Comment by deepfire** [comment]
@dcoutts raised a complicated question of whether we want Dhall, or maybe perhaps we could settle for just YAML. We've agonised over details with @cleverca22 for a while, and that's the rough summary:

1. Dhall configs have richer and hence more complex semantic, so therefore are less user-serviceable than the JSON/YAML (and also less familiar).
1. Using Dhall adds more complexity. In one instance, if we were to use Dhall in Daedalus, we'd have to either keep the extra step of Dhall->YAML transformation, or we would have to use https://github.com/Profpatsch/dhall-js
1. Dhall does quite strong type-checking out-of-the-box, and while we could use YAML validation by simply loading it using Aeson, that would not benefit from Dhall's stronger types, and better messages.
1. Dhall allows factoring of the configuration into separate files -- JSON/YAML have no mechanism for inclusion.
1. Dhall enables expression of context-dependent variability of configs by:
   - inclusion (i.e. you can import context-dependent subexpressions)
   - functional computation over context-dependent values
   We can see how this works in Daedalus:  https://github.com/input-output-hk/daedalus/tree/master/installers/dhall -- cluster and OS dependent pieces are factored, and have computations defined over them.
   YAML/JSON, in general would require having a product of all context-dependent axes to allow the same flexibility -- resulting in a maze of similar, but not quite files.
   This negative aspect of YAML/JSON could be somewhat compensated by moving some of the environment-dependency logic into the Haskell code (so we could have less than a full all-env-axes product of config files), but that would be adding complexity that could've otherwise been kept outside.
