### ISSUE TITLE
Improve handling of the environment variables in the launcher

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#325]
We have the test configuration for the launcher here - https://github.com/input-output-hk/cardano-shell/blob/master/cardano-launcher/configuration/launcher/launcher-config.demo.yaml and here - https://github.com/input-output-hk/cardano-shell/blob/master/cardano-launcher/configuration/launcher/launcher-config-demo.windows.yaml.

What we do miss is some of the variables in other config files (in that directory as above).
For example, we have a variable called `DAEDALUS_CONFIG` that we have to provide.

It would be much simpler if we could have a CLI to provide this path.

**Comment by ksaric** [comment]
@HirotoShioi @cleverca22 Comments?

**Comment by HirotoShioi** [comment]
To my knowledge, in order to achieve this, we need to do 3 things:

1. We have to make adjustment to the CLI to add extra optional argument
2. The script which launches the cardano-launcher must provide an argument
3. The cardano-launcher must be capable of setting the correct value (i.e. it must be able to do exactly what this nix script is doing) https://github.com/input-output-hk/daedalus/blob/develop/installers/nix/linux.nix#L29-L49
