### ISSUE TITLE
Migrate configuration.yaml to Haskell

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#8]
The configuration file (https://github.com/input-output-hk/cardano-sl/blob/develop/lib/configuration.yaml) is too large and contains things that are really not configurations.
They would be mostly constants.

The task is to create a Haskell module on top of https://github.com/input-output-hk/cardano-shell/pull/7 which contains all this information _in this repository_. 
There is a common structure, so let's use a common structure.

**Comment by erikd** [comment]
The thing to note is that I suspect some of the item in that configuration object are not even needed in the post OBFT version. Anything to do with the VSS (verifiable secret sharing), LRC, SSC can probably be dropped because they are not relevant for OBFT and probably different for the new Ouroboros protocols.

**Comment by robcohen** [comment]
Created a bunch of data types for the configuration.

**Comment by robcohen** [comment]
Compiled a description of the variables in one place for quick ref: https://github.com/input-output-hk/cardano-shell/blob/robcohen/GH-8-configuration-yaml-migration/configuration.md

Still attempting to determine a metric to find which variables should be hardcoded vs not.

**Comment by robcohen** [comment]
I kindly request that my commits be reviewed when possible. There is a CardanoConfig for both dev and mainnet.
